# Generated by Django 3.2 on 2021-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210503_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.CharField(max_length=25),
        ),
    ]
